# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
