# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldapp', '0003_auto_20180529_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfo',
            name='bpub_date',
        ),
    ]
