# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldapp', '0004_remove_bookinfo_bpub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='bprice',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='btitle',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='hcontent',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='hgender',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='hname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
