# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldapp', '0005_auto_20180529_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='bauthor',
            field=models.CharField(default='', max_length=10),
        ),
    ]
