# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldapp', '0006_bookinfo_bauthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default='', max_length=20)),
                ('paddress', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
